import { OnInit, EventEmitter } from '@angular/core';
export declare class FoxCalendar implements OnInit {
    _month: number;
    _hasSelect: any[];
    hasSelect: any[];
    month: number;
    _year: number;
    year: number;
    _day: number;
    day: number;
    _hour: number;
    hour: number;
    _minute: any;
    minute: number;
    _lastDate: Date;
    lastDate: Date;
    _timeLen: number;
    timeList: any[];
    timeLen: number;
    hasSelector: boolean;
    hasHeader: boolean;
    isRow: boolean;
    multi: boolean;
    onSelect: EventEmitter<any>;
    daySelect: EventEmitter<any>;
    list: any[];
    minDate: any;
    maxDate: any;
    btnPrevYearDisable: boolean;
    btnPrevMonthDisable: boolean;
    btnNextYearDisable: boolean;
    btnNextMonthDisable: boolean;
    _timeStart: any;
    timeStart: any;
    _timeEnd: any;
    timeEnd: any;
    constructor();
    ngOnInit(): void;
    setSelect(): void;
    onTouch(e: any): void;
    createTimeList(): void;
    setMinDate(val?: Date): void;
    setMaxDate(val?: Date): void;
    canUse(type?: string): {
        active: boolean;
        prev: boolean;
        normal: boolean;
        disable: boolean;
        next: boolean;
    };
    selectTime(item: any): void;
    select(item: any): void;
    finish(data: any): void;
    udpate(): void;
    create2(): void;
    create(): void;
    createNextMonth(): void;
    createPrevMonth(): void;
    createPrevYear(): void;
    createNextYear(): void;
    daysInMonth(month: number, year: number): number;
    weekInMonth(month: number, year: number): number;
    isInRange(date: any): boolean;
    updateSelect(year: number, month: number): void;
    getNowFormatDate(date: Date, fmt: string): string;
}
